/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#1173d4",
        "background-light": "#f6f7f8",
        "background-dark": "#101922",
        surface: "#f8f9fa",
        primary: "#003d9b",
        green1: "#08DA51",
        red: "#B44A52",

        "primary-container": "#0052cc",
        "surface-container": "#eceef0",
        secondary: "#505f76",
        outline: "#76777d",
        "on-tertiary-container": "#009668",
        "surface-variant": "#e0e3e5",
        "on-error": "#ffffff",
        "secondary-fixed": "#d3e4fe",
        "primary-container": "#131b2e",
        "surface-container-highest": "#e0e3e5",
        surface: "#f7f9fb",
        tertiary: "#000000",
        "secondary-container": "#d0e1fb",
        "on-tertiary-fixed-variant": "#005236",
        "on-secondary-container": "#54647a",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        background: "#f7f9fb",
        "tertiary-container": "#002113",
        "on-primary-container": "#7c839b",
        "on-tertiary-fixed": "#002113",
        "tertiary-fixed": "#6ffbbe",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#bec6e0",
        "outline-variant": "#c6c6cd",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "tertiary-fixed-dim": "#4edea3",
        error: "#ba1a1a",
        "inverse-surface": "#2d3133",
        "surface-tint": "#565e74",
        "on-primary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "on-surface": "#191c1e",
        "on-error-container": "#93000a",
        "surface-bright": "#f7f9fb",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed": "#0b1c30",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-background": "#191c1e",
        "on-surface-variant": "#45464d",
        "on-primary-fixed": "#131b2e",
        "primary-fixed": "#dae2fd",
      },
      fontFamily: {
        display: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      keyframes: {
        fadeInUp: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
      },
      animation: {
        fadeInUp: "fadeInUp 1s ease-out forwards",
        fadeIn: "fadeIn 1.2s ease-out forwards",
      },
    },
  },
  plugins: [],
};
